version: '3.5'

services:
    mqttbbr:
        build: .
        restart: 'unless-stopped'
        env_file:
            - .physics_env
        ports:
            - 8883:8883
        volumes:
            - './persist/mqttbroker:/persist/'
        networks:
            - physicsServices

    mongodb:
        image: mongo
        restart: 'unless-stopped'
        ports:
            - '27017:27017'
        env_file:
            - .physics_env
        volumes:
            - './persist/mongodb:/data/db'
            - './docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'

        networks:
            - physicsServices

networks:
    physicsServices:
        driver: bridge
        name: physicsServices
